### ISSUE TITLE
'compat' import error

### ISSUE THREAD

**Issue by kornsn** [douglas-treadwell/marshmallow-models#2]
```
...
    from marshmallow_models import Model
../../env/lib/python3.6/site-packages/marshmallow_models/__init__.py:1: in <module>
    from .models import Model, NestedModel
../../env/lib/python3.6/site-packages/marshmallow_models/models.py:7: in <module>
    from compat import with_metaclass
E   ModuleNotFoundError: No module named 'compat'
```

Maybe it should be smth like `from compat import with_metaclass` -> `from .compat import with_metaclass`?

**Comment by pkarp0** [comment]
This is still happening in version 0.2.0.
pip install marshmallow-models
python
>>> from marshmallow_models import Model
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/marshmallow_models/__init__.py", line 1, in <module>
    from .models import Model, NestedModel
  File "/usr/local/lib/python3.6/site-packages/marshmallow_models/models.py", line 7, in <module>
    from compat import with_metaclass
ModuleNotFoundError: No module named 'compat'
